### ISSUE TITLE
Suggestion: Nothing being played

### ISSUE THREAD

**Issue by BKeyport** [jclarke0000/MMM-MyScoreboard#12]
For leagues that are currently "Out of Season" or off for the day, can we get output like "[league name] - No games scheduled" - This would prevent blank screens in my case, where I have MMM-Carousel running to page between sports. 

"MLB - No Games Scheduled" 
"NBA - No Games Scheduled" 
"NCAAF - No Games Scheduled" 
etc. 

Thanks!

**Comment by jclarke0000** [comment]
The module intentionally hides sports that have no games scheduled for your current config.  This keeps the space used by the module to a minimum.
