### ISSUE TITLE
Scroes and game status not displaying

### ISSUE THREAD

**Issue by Gavin-McLeod** [jclarke0000/MMM-MyScoreboard#13]
It would appear that, at least for NHL, there are no scores or game status displaying.

**Comment by drippyer** [comment]
This is also the case for me. 

It is not just NHL being affected, all sports seem to have stopped displaying scores. All games show only the start time which does not change to the score at game time.

**Comment by hoveeman** [comment]
I noticed this today as well. NCAA Men’s basketball scores are showing correctly, but NFL and MLS is not showing scores for me today.

**Comment by vincep5** [comment]
the feed http://www.sportsnet.ca/wp-content/files/scoreboard.json doesn't look like it has the right objects for showing final scores anymore.  It handles scores for a majority of sports for this project :   Provides scores for
    NHL (National Hockey League)
    NFL (National Football League)
    NBA (National Basketball Association)
    CFL (Canadian Football League)
    MLS (Major League Soccer)
    MLB (Major League Baseball)

**Comment by Gavin-McLeod** [comment]
Did some investigating and found that for at least the NHL the scores are recorded in http://site.api.espn.com/apis/site/v2/sports/hockey/nhl/scoreboard?dates=yyyymmdd

From that I can tell that on 20181110 the Canucks lost to the Sabres 5-4 in a shootout.

I guess there might have been a change in how ESPN is delivering data?

**Comment by vincep5** [comment]
ESPN has it, but the code isn't using ESPN.  The current code uses that sportsnet api I mentioned in the previous comment.  Maybe I'll play around with the code and let you know if I can fix it in my fork of this code.

**Comment by Gavin-McLeod** [comment]
I see.  I was noticing both feeds were in use in the code.

**Comment by vincep5** [comment]
Hey, I have updated my fork tonight.  Perhaps you can pull my version of this code and try it out.  I swapped out NHL and other american sports to use ESPN instead of that Canadian feed.  It's the same steps just that you have to point to my repository : https://github.com/vincep5/MMM-MyScoreboard

**Comment by hoveeman** [comment]
@vincep5 Thanks! I changed my MagicMirror to use your fork. Everything started up fine. I will report back once some games start.

**Comment by Gavin-McLeod** [comment]
@vincep5 - thanks.  I'll switch over when i get home this evening and try it out.

**Comment by Gavin-McLeod** [comment]
Looking good for NHL and NBA
Thanks

**Comment by jclarke0000** [comment]
FYI, Module has been updated to use the new Sportsnet feed.  Fixes NHL, NFL, CFL, MLS and MLB.

**Comment by DizzyDwarf0013** [comment]
This seems to be an issue again. The scores don't update unless I refresh.  Is there another Sportsnet feed this needs to be update to?
