### ISSUE TITLE
Does the Module Not Display Playoff Scores?

### ISSUE THREAD

**Issue by ChrisKvneb** [jclarke0000/MMM-MyScoreboard#17]
I just installed the module and it seems to run well but when I try to add the Boston Celtics to the module it doesn't display their scores even though they have recently had games. Is there any way to have it display whatever the most recent score for whatever team(s) you've selected?

**Comment by jclarke0000** [comment]
The module only displays one day's worth of scores.  You can adjust the `rolloverHours` config parameter to change the time at which yesterday's scores stop being displayed and today's score start being displayed.
