### ISSUE TITLE
results

### ISSUE THREAD

**Issue by kr1st4ps** [jclarke0000/MMM-MyScoreboard#19]
At first the module worked all right and showed me at what time the game is going to be, but when i turned my MagicMirror the next morning, results of the game didn't show. I tried rolloverhours, but that didn't help. Could this be because of my timezone?

**Comment by jclarke0000** [comment]
Yes time zone could be the issue.  That is the purpose of the `rolloverHours` config parameter.You'll need to figure out the correct number of hours to set based on your time zone and the time zone the games occur.  Both of the providers in my feed work on US/Eastern time.  If your time zone is in Europe, for example, you would need to account for the difference in time zone AND the difference in hours for display.  So let's say you wanted to have yesterday's scores visible until noon.  You would need to set `rolloverHours` to 12 hours + the difference in time zone.  If you're in the UK, this difference is +5 hours.  So you would set `rolloverHours` to 17.
