### ISSUE TITLE
Dual MLB

### ISSUE THREAD

**Issue by catncpa** [jclarke0000/MMM-MyScoreboard#20]
First off - awesome module & thanks!

Trying to setup Today's & Yesterday's scores so added two versions in the config - one with rollover one w/o.
The soccer leagues worked perfectly but the MLB always shows the same info in both module. Sometimes both Today sometimes both Yesterday. Tried several different variations on the rollover number but never worked.
Any ideas? Thanks!

**Comment by jclarke0000** [comment]
It works with  soccer leagues, as they are provided by ESPN, which will work with your setup.  But MLB is provided by SNET, and it is fetched in a different way.  You'll only ever get one set of scores with SNET.

You could modify the code to retrieve MLB with ESPN's feed.  Look at MMM-MyScoreboard.js

```
  supportedLeagues: {
    //North American Leagues
    "NBA": {provider: "ESPN", logoFormat: "svg"},
    "NHL": {provider: "SNET", logoFormat: "svg"},
    "NFL": {provider: "SNET", logoFormat: "svg"},
    "CFL": {provider: "SNET", logoFormat: "svg"},
    "MLB": {provider: "SNET", logoFormat: "svg"},
    "MLS": {provider: "SNET", logoFormat: "url", homeTeamFirst: true},
    "NCAAF": {provider: "ESPN", logoFormat: "url"},
    "NCAAM": {provider: "ESPN", logoFormat: "url"},
    "NCAAM_MM": {provider: "ESPN",logoFormat: "url"},
    "NCAAW": {provider: "ESPN", logoFormat: "url"},
    "WNBA": {provider: "ESPN", logoFormat: "url"},
   ```
   
On line 49 change:
```
"MLB": {provider: "SNET", logoFormat: "svg"},
```
to
```
"MLB": {provider: "ESPN", logoFormat: "svg"},
```

Note that by doing this, some team short codes will change -- SNET and ESPN don't always use the same shortcodes.  So if you notice some logos not displaying, for example, you'll need to rename the logo files found under `logos/MLB` with the ESPN shortcode.  Similarly, if you've set your config to follow a specific team, and you're not seeing scores, it's likely the same shortcode mismatch issue.
