### ISSUE TITLE
Score alignment

### ISSUE THREAD

**Issue by ITCTE108** [jclarke0000/MMM-MyScoreboard#23]
How do I change the position of the scores to be the top left. The My Scoreboard shows up on the top left but the scores are in the center of the mirror.

**Comment by jclarke0000** [comment]
This sounds like a CSS problem.  try editing your `custom.css` file to limit the width of either the MMM-MyScoreboard module or the top-left container.

Here is what I have in my mirror, and I use the Scoreboard in the top-left region as well:

```
.region.left .module-content {
  max-width: 300px;
  min-width: 300px;
}

```
