### ISSUE TITLE
Missing logo for Shanghai Sharks

### ISSUE THREAD

**Issue by ghost** [jclarke0000/MMM-MyScoreboard#24]
They popped up on the schedule today with a game against the Houston Rockets and the logo is missing.

https://en.wikipedia.org/wiki/Shanghai_Sharks

**Comment by blinkinfo** [comment]
"SHANGHAI SHARKS" is not a NBA team!

**Comment by thedfordfox** [comment]
> "SHANGHAI SHARKS" is not a NBA team!

Did you even read my post? The NBA did dozens of exhibition games against teams outside the US last season.
