### ISSUE TITLE
Missing logo for Franca

### ISSUE THREAD

**Issue by ghost** [jclarke0000/MMM-MyScoreboard#26]
Missing logo for the Brazilian NBA team "Franca".

Also in the HTML output, the image name is "FRAN .svg" with a space before the dot.

Here's some of the text from the ESPN API that might help.

`{"id":"401163116","uid":"s:40~l:46~e:401163116","date":"2019-10-04T23:30Z","name":"Franca Franca at Brooklyn Nets","shortName":"NULL @ BKN","season":{"year":2020,"type":1},"competitions":[{"id":"401163116","uid":"s:40~l:46~e:401163116~c:401163116","date":"2019-10-04T23:30Z","attendance":0,"type":{"id":"1"},"timeValid":true,"neutralSite":false,"conferenceCompetition":false,"recent":false,"venue":{"id":"3559","fullName":"Barclays Center","address":{"city":"Brooklyn","state":"NY"},"capacity":17732,"indoor":false},"competitors":[{"id":"17","uid":"s:40~l:46~t:17","type":"team","order":0,"homeAway":"home","team":{"id":"17","uid":"s:40~l:46~t:17","location":"Brooklyn","name":"Nets","abbreviation":"BKN","displayName":"Brooklyn Nets","shortDisplayName":"Nets","color":"000000","alternateColor":"ffffff","isActive":true,"venue":{"id":"1826"},"links":[{"rel":["clubhouse","desktop","team"],"href":"http://www.espn.com/nba/team/_/name/bkn/brooklyn-nets","text":"Clubhouse","isExternal":false,"isPremium":false},{"rel":["roster","desktop","team"],"href":"http://www.espn.com/nba/team/roster/_/name/bkn/brooklyn-nets","text":"Roster","isExternal":false,"isPremium":false},{"rel":["stats","desktop","team"],"href":"http://www.espn.com/nba/team/stats/_/name/bkn/brooklyn-nets","text":"Statistics","isExternal":false,"isPremium":false},{"rel":["schedule","desktop","team"],"href":"http://www.espn.com/nba/team/schedule/_/name/bkn","text":"Schedule","isExternal":false,"isPremium":false},{"rel":["photos","desktop","team"],"href":"http://www.espn.com/nba/team/photos/_/name/bkn","text":"photos","isExternal":false,"isPremium":false},{"rel":["scores","sportscenter","app","team"],"href":"sportscenter://x-callback-url/showClubhouse?uid=s:40~l:46~t:17&section=scores","text":"Scores","isExternal":false,"isPremium":false},{"rel":["draftpicks","desktop","team"],"href":"http://www.espn.com/nba/draft/teams/_/name/bkn/brooklyn-nets","text":"Draft Picks","isExternal":false,"isPremium":true},{"rel":["transactions","desktop","team"],"href":"http://www.espn.com/nba/team/transactions/_/name/bkn","text":"Transactions","isExternal":false,"isPremium":false},{"rel":["injuries","desktop","team"],"href":"http://www.espn.com/nba/team/injuries/_/name/bkn","text":"Injuries","isExternal":false,"isPremium":false},{"rel":["depthchart","desktop","team"],"href":"http://www.espn.com/nba/team/depth/_/name/bkn","text":"Depth Chart","isExternal":false,"isPremium":false}],"logo":"https://a.espncdn.com/i/teamlogos/nba/500/scoreboard/bkn.png"},"score":"0","records":[{"name":"All Splits","abbreviation":"Total","type":"total","summary":"0-0"},{"name":"Home","type":"home","summary":"0-0"},{"name":"Road","type":"road","summary":"0-0"}]},{"id":"112638","uid":"s:40~l:46~t:112638","type":"team","order":1,"homeAway":"away","team":{"id":"112638","uid":"s:40~l:46~t:112638","location":"Franca","name":"Franca","displayName":"Franca","shortDisplayName":"Franca","isActive":false,"links":[]},"score":"0"}],"notes":[],"status":{"clock":0.0,"displayClock":"0.0","period":0,"type":{"id":"1","name":"STATUS_SCHEDULED","state":"pre","completed":false,"description":"Scheduled","detail":"Fri, October 4th at 7:30 PM EDT","shortDetail":"10/4 - 7:30 PM EDT"}},"broadcasts":[{"market":"national","names":["NBATV"]},{"market":"home","names":["YES"]}],"tickets":[{"summary":"Tickets as low as $8","numberAvailable":2763,"links":[{"href":"https://www.vividseats.com/nba-basketball/brooklyn-nets-tickets/nets-10-4-3196983.html?wsUser=717"},{"href":"https://www.vividseats.com/venues/barclays-center-tickets.html?wsUser=717"}]}],"startDate":"2019-10-04T23:30Z","geoBroadcasts":[{"type":{"id":"1","shortName":"TV"},"market":{"id":"1","type":"National"},"media":{"shortName":"NBATV"},"lang":"en","region":"us"},{"type":{"id":"1","shortName":"TV"},"market":{"id":"2","type":"Home"},"media":{"shortName":"YES"},"lang":"en","region":"us"}]}],"links":[{"language":"en","rel":["summary","desktop","event"],"href":"http://www.espn.com/nba/game?gameId=401163116","text":"Gamecast","shortText":"Gamecast","isExternal":false,"isPremium":false}],"status":{"clock":0.0,"displayClock":"0.0","period":0,"type":{"id":"1","name":"STATUS_SCHEDULED","state":"pre","completed":false,"description":"Scheduled","detail":"Fri, October 4th at 7:30 PM EDT","shortDetail":"10/4 - 7:30 PM EDT"}}}]}`

**Comment by jclarke0000** [comment]
With the latest release, I have switched to use the images provided in the feed.  This means a logo should always be present.  However the logos provided in the feed are normally displayed on a white background, so if the logo is dark or black, it won't be visible against a typical Magic Mirror install with a black background.
