### ISSUE TITLE
Maxentries / Rotationspeed; how to make this module even better then its current awsomeness

### ISSUE THREAD

**Issue by Bernard-h** [jclarke0000/MMM-MyScoreboard#31]
Hi Jclarke, fist of all many thanks for developing the module it is one of my absolute favorites. I have a question which I think many of us bump into. To clarify my request I need an example. 

When following some sports or leagues the amount of games on a given date or evening can be very significant. Just about a month ago we had the first elimination round in european soccer. On a given evening some 32 games are being played simultaniously. The amount of space the module requires at that point, distorts the entire view of the mirror by overlapping and cropping other modules. 

Would it be possible to leave everything as is, but adding 2 parameter: maxdisplay and rotationspeed. That way the module can stay clean and size-friendly yet still have the option to get all the info users may request. 

That would be awsome ! Would someone who is good at coding be willing to look at this ? 

Keep up the good work and thanks in advance.

**Comment by verotheelf** [comment]
Do you know if someone already created this feature? Came here looking for the same thing. If not, I'm going to fiddle around and see if I can get something working.

**Comment by Bernard-h** [comment]
I say go for it! :)

**Comment by DeanW2510** [comment]
Was any progress made with this? This is the exact request I have of the module too.

Thanks in advance!

**Comment by jclarke0000** [comment]
@Bernard-h I looked into adding the ability to include rotation into this, but the way the module is architected would require significant changes to the code.  However, there is a way for you to get what you want.  You can configure multiple versions of MMM-MyScoreboard in your config, each with a different set of sports and teams.  then you could use a module such as MMM-Carousel (https://github.com/barnabycolby/MMM-Carousel) to rotate between them
