### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by arhumman** [jclarke0000/MMM-MyScoreboard#32]
hey, i used the install script to download and followed the steps but the terminal spat this out 
pi@raspberry:~/MagicMirror/modules/MMM-MyScoreboard $ npm install
added 59 packages from 65 contributors and audited 75 packages in 3.388s
found 5 vulnerabilities (2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

if i run npm audit fix, it fixes 1 vulnerabilities. is this regular and what should i do? thanks.

**Comment by jclarke0000** [comment]
@arhumman This is Node letting you know that some of the libraries the modules uses have know issues, but the module would still have worked.  In any case, the library in question is deprecated, and I have replaced with a new one that is currently supported.  The module now has no vulnerabilities at the moment.
