### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by sigel** [jclarke0000/MMM-MyScoreboard#37]
Tried to use this for NFL without anything showing

**Comment by aseadc86** [comment]
I've noticed my module was getting spotty and no it's showing at all.  Have you gotten yours to work?

**Comment by Blaze212** [comment]
I have the NFL and English Premier League working as of today 12/6/2020. 
The module will hide itself if there are no games for the current day for any of the teams you have set in your config file.

I thought the module was broken yesterday when trying to get it set up because none of the teams that I had configured had games on Saturday. But now that its Sunday, both live games and completed games showed up.

**Comment by trentsloan09** [comment]
Blaze, can you post what your config file looks like for the Scoreboard? Trying to get it up for the Monday night game and I can't get it to show. I even copied his little example. 

Unless it doesn't show games that currently active? That wouldn't make much sense though I would think.

**Comment by Blaze212** [comment]
It will only show games if there is/was a game for today.  So your module will not display until Sunday.
There were premier league games today 12/17, so this should get the module to show up for today.
```
{
			module: "MMM-MyScoreboard",
			position: "top_right",
			classes: "default everyone",
			header: "Scoreboard",
			config: {
			  showLeagueSeparators: true,
			  colored: true,
			  viewStyle: "mediumLogos",
			  sports: [
				
				{
				  league: "NFL",
				  teams: ["MIN", "DAL"]
				},
				{
				  league: "ENG_PREMIERE_LEAGUE"

				},
				{
					league: "UEFA_CHAMPIONS"
				},
				{
					league: "FIFA_WORLD_CUP"
				},
				{
					league: "NCAAF",
					teams: ["TEX", "LSU", "TAMU"]
				  },
			  ]
		  
			}
		  }
```

**Comment by trentsloan09** [comment]
Yeah mine looks the same, I changed my NFL teams to the ones playing tonight just so I could get something to show up and it never did. I dont get why yours would lol

**Comment by Blaze212** [comment]
1. Can you send me your config?  
2. I added "LAC" to the NFL section and the game popped up. (The Raider logo was blank, but the chargers showed up)

**Comment by sigel** [comment]
hmm Strange.... I added NFL, NBA, but my module is stuck on "Loading..."

**Comment by trentsloan09** [comment]
I am currently at work, as soon as I get home I will post it. Im like 99% sure that its exactly the same though lol

**Comment by trentsloan09** [comment]
{
			module: "MMM-MyScoreboard",
			postion: "top_center",
			classes: "default everyone",
			header: "Scoreboard",
			config: {
				showLeagueSeperators: true,
				colored: true,
				viewStyle: "mediumLogos",
				rolloverHours: 24,
				sports: [
				{
					league: "NFL",
					teams: ["LAC"]							
				},

				{
					league: "NCAA_MM",
					groups: ["SEC", "TOP 25"]
				},

//				{
//					league: "NBA",
//					teams: ["","","","","",""]
//				},
				]			
				}
		},

**Comment by Blaze212** [comment]
You are missing the "i" in position!   That should fix your problems. I copied you config as is and when I fixed the ```postion``` it showed up.
