### ISSUE TITLE
MMM-MyScoreboard Module not displaying

### ISSUE THREAD

**Issue by ryansuchomel** [jclarke0000/MMM-MyScoreboard#38]
I have several other modules working just fine.  I'm using MMM-Carousel as well and I have MMM-MyScoreboard on my second slide.  I've tried getting rid of Carousel for a bit to see if I could get MyScoreboard working but it just shows the header for like one second and then there is nothing.  Here is my config portions that include Carousel and MyScoreboard config (I apologize, the json formatting didn't stick with the copy/paste:

{
module: "MMM-Carousel",
position: 'bottom_bar',
config: {
transitionInterval: 60000,
showPageIndicators: true,
showPageControls: true,
ignoreModules: ['clock', 'alert', 'calendar', 'MMM-GooglePhotos'],
mode: 'slides',
slides: [
['currentweather', 'weatherforecast', 'MMM-PaprikaMenu', 'MMM-Todoist'],
['MMM-MyScoreboard', 'newsfeed', 'MMM-Jast'],
],
},
},
  {
module: "MMM-MyScoreboard",
position: "top_right",
classes: "default everyone",
header: "My Scoreboard",
config: {
showLeagueSeparators: true,
colored: true,
viewStyle: "mediumLogos",
rolloverHours: 10,
showRankings: true,
sports: [
{
league: "MLB",
teams: ["MIL"]
},
{
league: "NFL",
teams: ["GB"]
},
{
league: "NHL",
teams: ["NSH"]
},
{
league: "NBA",
teams: ["MIL"]
},
{
league: "NCAAF",
teams: ["WIS"]
},
{
league: "NCAAM",
teams: ["WIS"]
},
],
},
},

**Comment by Blaze212** [comment]
I have the NFL and English Premier League working as of today 12/6/2020.
The module will hide itself if there are no games for the current day for any of the teams you have set in your config file.

I thought the module was broken yesterday when trying to get it set up because none of the teams that I had configured had games on Saturday. But now that its Sunday, both live games and completed games showed up. Tomorrow the module will be hidden again since none of those teams play on Monday.

**Comment by bflbarlow** [comment]
The ESPN API utilizes "WISC" for the team abbreviation for at least NCAAM (_haven't taken a look at NCAAF_). The Badgers weren't showing up on my MagicMirror while the Bucks would so I traced it back to the ESPN API.

I also had to change the /home/pi/MagicMirror/modules/MMM-MyScoreboard/logos/NCAAM image file name from "WIS.png" to "WISC.png" to get the motion W to show. 

Here's my current Config that works great.

```
{
module: "MMM-MyScoreboard",
position: "top_center",
classes: 'nighttime_off',
header: "My Scoreboard",
config: {
    	showLeagueSeparators: true,
    	colored: true,
    	rolloverHours: 10,
    	viewStyle: "mediumLogos",
    	shadeRows: false,
    	highlightWinners: true,
    	showRankings: true,
    	viewStyle: "mediumLogos",
	 sports: [ 	{league: "NCAAM", teams: ["WISC"]},
			{league: "NFL", teams: ["GB"]},
			{league: "NBA", teams: ["MIL"]},
			]
	}
},
```
Also... #OnWisconsin :)

**Comment by jclarke0000** [comment]
ESPN's feed has been unreliable in the past, however it's currently working.  With the latest update, I've changed the code to use HTTPS instead of HTTP when requesting data from ESPN.  Also, the latest update has Wiconsin's short code corrected to `WISC`
