### ISSUE TITLE
ENGLISH PREMEIR LEAGUE

### ISSUE THREAD

**Issue by bennykoo** [jclarke0000/MMM-MyScoreboard#40]
Hi,

For some reason the ENGLISH PREMIER LEAGUE isn't working in this module and on my standings module. Is ther a reason for that? Maybe ESPN have changes their code for that leauge?

**Comment by Bernard-h** [comment]
I had a quick look on the website and coding and according to espn website its still eng.1 Not really sure why its not working must be the league code altough i cant find the correct one on the website.

**Comment by jclarke0000** [comment]
ESPN's feed has been unreliable in the past.  EPL is currently working, and with the latest update I've changed the ESPN provider code to use HTTPS instead of HTTP in an attempt to improve reliability.
