### ISSUE TITLE
MMM-MyScoreboard not displaying

### ISSUE THREAD

**Issue by BrotherBruce25** [jclarke0000/MMM-MyScoreboard#43]
I am trying to add this module to the mirror and for some reason it is not appearing. I made sure the teams I have are playing live and I made sure I get no errors on start up. Here is my config: {
			module: "MMM-MyScoreboard",
			position: "top_bar",
			classes: "default everyone",
			header: "My Scoreboard",
			config: {
				showLeagueSeparators: true,
				colored: true,
				viewStyle: "mediumLogos",
				sports: [
						{
							league: "NBA",
							teams: ["IND", "POR"]
						},
						{
							league: "MLB",
							teams: ["NYY"]
						},
						{
							league: "NFL",
							teams: ["NYG"]
						},
					]
				},
		},

**Comment by shak4031** [comment]
I believe you have an extra "," in your 2nd to last parentheses.

**Comment by jclarke0000** [comment]
@shak4031 is correct.  Remove the command after the second-last curly brace.
