### ISSUE TITLE
How can i show both todays matches and yesterdays results

### ISSUE THREAD

**Issue by tammar10** [jclarke0000/MMM-MyScoreboard#44]
How can i show both todays matches and yesterdays results.

when I change the 

rolloverHours: 24, //hours past midnight to show the pervious day's scores

it does only show the pervious day's scores but not todays scores

**Comment by jclarke0000** [comment]
Setting the `rolloverHours` parameter won't give you a way to display BOTH yesterday AND today's games.  It will only adjust the threshold for when the module stops polling for yesterday's scores and starts polling for today's.  This module will only display schedule and scores for one day at a time.  Changing this will require a significant change to the app's architecture.
