### ISSUE TITLE
ENG_PREMIERE_LEAGUE - English Premier League not working

### ISSUE THREAD

**Issue by shak4031** [jclarke0000/MMM-MyScoreboard#48]
My configuration for MLB works fine, but Premiere League does not.

{
  module: "MMM-MyScoreboard",
  position: "bottom_left",
  classes: "default everyone",
  header: "Soccer Scoreboard",
  config: {
    showLeagueSeparators: false,
    colored: true,
    viewStyle: "mediumLogos",
    sports: [
      {
        league: "ENG_PREMIERE_LEAGUE",
        teams: ["LIV", "MNC", "CHE", "MAN"]
      },
    ]

  }
},

**Comment by jclarke0000** [comment]
EPL is provided by ESPN's feed which has been unreliable in the past.  It is currently working and with the latest update I've changed the ESPN provider to use HTTPS instead of HTTP, in an attempt to improve this feed.
