### ISSUE TITLE
NHL - Seattle Kraken logo missing

### ISSUE THREAD

**Issue by iamjmax** [jclarke0000/MMM-MyScoreboard#51]
See title, just shows a black box with ‘SEA’ in it

**Comment by antonioasaro** [comment]
I got the logo from here: https://www.vector69.com/2021/07/seattle-kraken-2020-logo-svg.html
Download the .svg, rename it to SEA.svg and plop it in the ~/MagicMirror/modules/MMM-MyScoreboard/logos/NHL directory (I used WinSCP to copy files to/from the Pi). You'll see a bunch of team logos in there already.

**Comment by iamjmax** [comment]
Thanks!
