### ISSUE TITLE
Add playoff games as groups

### ISSUE THREAD

**Issue by JOLLY6R33NGIANT** [jclarke0000/MMM-MyScoreboard#52]
Curious if it’s possible to add playoff series as groups. I’d like to be able to see the scores of my team during the season and then come playoffs be able to see all the scores of the playoff games without adding the teams in the playoffs specifically.

**Comment by jclarke0000** [comment]
The way groups are handled in the module, this would require an update each year and with each playoff round.  Instead, if you just add the league to your config, but don't specify and teams or groups, then you will get all of the scheduled games during the playoffs -- essentially giving you the experience you're asking for.
