### ISSUE TITLE
NCAAM and NCAAF not working

### ISSUE THREAD

**Issue by jwoodsman10** [jclarke0000/MMM-MyScoreboard#55]
Other sports have been working fine such as the NFL, NHL and NBA. However NCAAF and NCCAM have not been showing up even when there are games in the top 25 and the teams that I have specified. Anyone have any suggestions? 

Here is my config.js

{
  module: "MMM-MyScoreboard",
  position: "bottom_right",
  classes: "default everyone",
  header: "My Scoreboard",
  config: {
    showLeagueSeparators: true,
    colored: true,
    viewStyle: "mediumLogos",
    sports: [   
      {
        league: "NCCAF",
        teams: ["UVA"],
	groups: ["Top 25"]
      },
      {
        league: "NHL",
        teams: ["WSH"]
      },
      {
        league: "NCCAM",
	teams: ["UVA"],
	groups: ["Top 25"]
      },
      {
        league: "NBA",
      },
       {
        league: "NFL",
      },
      {
        league: "NCAAM_MM",
        label: "March Madness"
      }
    ]

  }
},

**Comment by teegray1124** [comment]
did ever get this fixed?

**Comment by jclarke0000** [comment]
ESPN's feed is sometime's unreliable.  It is currently working as 2-Oct-2022, and I can confirm it has been providing data for NCAAF for the last couple of days.
