### ISSUE TITLE
Nothing shows

### ISSUE THREAD

**Issue by Brew-tus** [jclarke0000/MMM-MyScoreboard#63]
I entered all the codes and when I run MagicMirror the area shows "My Scoreboard, Loading" then disappears but then nothing shows for scores. My other modules load just fine. Here is how I have it entered. Dont get any errors; have I done something wroing?

		{
			
			module: "MMM-MyScoreboard",
			position: "top_center",
			classes: "default everyone",
			header: "My Scoreboard",
			config: {
			showLeagueSeparators: true,
			colored: true,
			rolloverHours: 10,
			viewStyle: "largeLogos",
			shadeRows: false,
			highlightWinners: true,
			rolloverHours: 10,
			showRankings: true,
			viewStyle: "largeLogos",
				sports: [ 	{league: "NCAAF", teams: ["NEB"]},
				{groups: ["Big Ten", "Top 25"]},
				{league: "NFL", teams: ["TB"]},
				{groups: ["American League", "National League"]},
				{league: "NHL", teams: ["CHI", "PIT", "TB"]},
				{groups: ["East", "West"]},
				{league: "MLB", teams: ["STL"]},
				{groups: ["American League", "National League"]},
				]
			}

**Comment by acer123acer123** [comment]
See this patch. It seems the URL has changed. Once this pull request is merged you can update your module and see the scores. If you don't want to wait, just manually update the URLs:  https://github.com/jclarke0000/MMM-MyScoreboard/pull/61

**Comment by jclarke0000** [comment]
SNET feed URL has been updated.  Do a `git pull` to get NFL, NHL and MLB working again.  NCAAF is pulled from a different source that had been sporadically problematic, but is now working again.  I can confirm NCAAF has been working for me for the last two days.
