### ISSUE TITLE
The module disappears showing nothing.

### ISSUE THREAD

**Issue by Egnos87** [jclarke0000/MMM-MyScoreboard#64]
The only word "MyScoreboard" appears for a few seconds and then disappears.

Hi, I tried to edit the SNET.js file by editing the links from https://d290qmen6zswb.cloudfront.net/ticker to https://mobile-statsv2.sportsnet.ca/ticker but nothing has changed.
I would just like to view the results of the Italian Serie A championship.
Here are the errors of the MM:

`[02.09.2022 10:52.55.068] [LOG]   [MMM-MyScoreboard] 2-Sep-22 10:52 ** ERROR ** Couldn't retrieve ITA_SERIE_A data for provider ESPN: Error: getaddrinfo ENOTFOUND site.api.espn.com
[02.09.2022 10:52.55.068] [LOG]   [MMM-MyScoreboard] http://site.api.espn.com/apis/site/v2/sports/soccer/ita.1/scoreboard?dates=20220902&limit=200`

`Starting module: MMM-MyScoreboard MMM-MyScoreboard.js:560 
All modules started!
MMM-MyScoreboard.js:552 
[MMM-MyScoreboard] Updating Scores module.js:195 
MMM-MyScoreboard is suspended.`

This is my simple configuration:
{
		  module: "MMM-MyScoreboard",
		  position: "top_right",
		  classes: "default everyone",
		  header: "My Scoreboard",
		  config: {
			showLeagueSeparators: true,
			colored: true,
			viewStyle: "mediumLogos",
			sports: [
			  {
				league: "ITA_SERIE_A",
				//teams: ["JUV"]
				//label: "Seria A TIM 2022/23"
			  }
					]
				}
		},

Can you help me?

Thanks.

**Comment by bam7** [comment]
I changed the URL about two weeks ago as suggested and it worked.   Now suddenly it isn't working anymore for me either.  When you hit the ticker URL directly, it doesn't send the score data back.   There has to be something else not working correctly.

**Comment by Egnos87** [comment]
I saw that the link to be replaced has nothing to do with ESPN and in my case it had no effect.

Also I believe that the espn provider is broken, because:

`data for provider ESPN: Error: getaddrinfo ENOTFOUND site.api.espn.com`

That module is 5 years old… these providers change things every year…

I hope someone fixes it because the module is really nice!

**Comment by Kayakbabe** [comment]
yep it's broken for me too. i'll bet espn changed things again. bummer.

**Comment by Kayakbabe** [comment]
or it might be a caching issue, I have this as my error
couldn't retrieve data for provider SNET: Error: getaddrinfo ENOTFOUND d290qmen6zswb.cloudfront.net
forcing a refresh does nothing either and the cloudfront server doesn't change.

**Comment by bam7** [comment]
It's definitely something with the feed from ESPN because it started to sporadically work for me this weekend.    Sometimes data just shows up and then maybe an hour later, it's empty.

**Comment by jclarke0000** [comment]
ESPN feed is currently working, and I've tested specifically with ITA_SERIE_A for the last couple of days.  It seems the ESPN feed is sometimes unreliable.  I'm using their official public API so it's not like I'm scraping some web page that can change on a whim. Unfortunately it's the only public free API that I know of that provides all of the world's soccer leagues.
