### ISSUE TITLE
looks like the api changed, is there an update for this module?

### ISSUE THREAD

**Issue by Kayakbabe** [jclarke0000/MMM-MyScoreboard#67]
looks like the api changed, is there an update for this module?
I was hoping to figure out why this stopped working in early sept 2022. 
I was digging around in the page source on espns api demos and it looks like they changed some things. However, It's hopeless mumbo jump for me. I hope Jclarke can update this. I sure liked seeing what games were coming up and the scores for college football in the US.

**Comment by sanj926** [comment]
https://github.com/jclarke0000/MMM-MyScoreboard/pull/61/commits/95e04209f42b49fc93b5e0c4e9d0f06429a5b5b0

**Comment by sanj926** [comment]
Look at the pull request I just commented.  I did that fix and it works again!  

Just need to replace the SNET.js with the new api address.

**Comment by DizzyDwarf0013** [comment]
Still not working for me, unfortunately. 

Edit:  Correct me if I'm wrong, but NCAAF is pulled from ESPN, not SNET. I've navigated to the API and located data, but I'm not able to get it to display.

**Comment by jclarke0000** [comment]
The SNET provider has been updated with the right URL.  A `git pull` will get you up and running again.  ESPN provider is working correctly. I can confirm NCAAF is working for me.
